Esri/data-collection-ios

data-collection/data-collection/View Controllers/Map View Controller/MapViewController+LocationSelection.swift

If a user has not authenticated and attempts to access the world geo-coder service, the ArcGIS Runtime SDK presents an authentication view controller modally. Now, setting the container view on the global SVProgressHUD ensures that the progress hud is presented within the view controller's view instead of on top of the window and no longer covers the presenting modal view controller.
To reproduce:
1. Launch app (using Trees of Portland).
2. Ensure user is logged out.
3. Add a new Tree feature.
When the authentication view controller presents, the ProgressHUD should no longer cover the presented view.

Improves UX when authenticating for world geocoder service.

---

data-collection/data-collection/AppContext/AppContext+Login.swift
data-collection/data-collection/Geocode Search/AppReverseGeocoderManager.swift

In case the services cache the previously used credentials. Now, with the geo-coder, we can guarantee the SDK to prompt for credentials when the user is not authenticated.
This can be tested following these steps:
1. Launch App (using Trees of Portland).
2. Log-in.
3. Add new Tree Feature.
_(App should not prompt for authentication)_
4. Log-out
5. Add new Tree Feature.
_(App should prompt for authentication)_

Forcibly removes credentials from geo-coder services.

---

data-collection/Resources/Info.plist

They are no longer needed since ArcGIS Online has updated the owning system URL.
This can be confirmed by checking [this URL](https://www.arcgis.com/sharing/rest/info?f=pjson) for key "owningSystemUrl". The url should use `https`.
To confirm this change works:
1. Launch App
2. Log-in to AGOL
This change works if no errors are thrown in Xcode.

Removes ATS: allowing arbitrary loads and exception domains.

---

data-collection/data-collection/Custom Behavior/CustomBehavior_TreeSymbology.swift

Changes update symbology custom behavior to update symbology when there are zero inspections for a tree.
To confirm this PR addresses the issue:
1. Launch app. (Using Trees of Portland, default)
2. Identify a tree on the map, ensure that tree has 1+ inspections.
_Note the color of the tree symbology_
3. Delete all of the inspections for that tree.
4. Return to the map view.
At this point the tree symbology should be black, representing no inspection.
If you add an inspection(s) to the tree, the symbology should reflect the color of the most recent inspection.

Improves app custom behavior: Tree symbology updates despite zero inspections.

---

data-collection/data-collection/AppConfiguration.swift
data-collection/data-collection/View Controllers/Map View Controller/MapViewController.storyboard

Small pop-up view: assigns higher horizontal compression resistance to (n) related records than that of the address label.
Before:
After:

Improves how the small pop-up view prioritizes label content.

---

data-collection/data-collection/Custom Behavior/CustomBehavior_IdentifyNeighborhood.swift
data-collection/data-collection/Custom Behavior/CustomBehavior_NewTreeCondition.swift
data-collection/data-collection/Custom Behavior/CustomBehavior_ReverseGeocode.swift
data-collection/data-collection/Custom Behavior/CustomBehavior_TreeSymbology.swift

This allows the parameter documentation to be parsed and shown in the correct place in quick help.
Before | After
------ | -----

Users parameter/parameters markup elements

---

data-collection/data-collection/Custom Views/PinDropView.swift
data-collection/data-collection/Custom Views/SlideNotificationView.swift
data-collection/data-collection/View Controllers/Related Records View Controllers/Related Records Popups View Controller/Field Cells/Base/PopupTextFieldCell.swift
data-collection/data-collection/View Controllers/Related Records View Controllers/Related Records Popups View Controller/RelatedRecordsPopupsViewController+Delegate.swift

In addition to being briefer, using the computed properties ensures that the returned value is always positive.

Use CGRect.width and CGRect.height

---

sdk_build

Sets Jenkins SDK build number to public `100.4.0`.
App functionality performs as expected.

Updates app to build for 100.4

---

data-collection/data-collection/Extensions/ArcGIS/AGSArcGISFeatureTable/AGSArcGISFeatureTable+Edit.swift

`refreshObjectID()` -> `refresh()` starting in `100.4.0`.

Updates AGSArcGISFeature deprecated method.

---

data-collection/data-collection/View Controllers/Map View Controller/MapViewController+SmallPopupView.swift

Defaults add related record button to hidden- unless first one to many related record table can add feature.
See issue: https://github.com/Esri/data-collection-ios/issues/139

Add Related Record Button Bugfix

---

data-collection/data-collection/View Controllers/Map View Controller/MapViewController.swift

When a new portal is set, the map view controller refreshes it's `mapViewMode` and `currentPopup`.

Refreshes MapViewController for newly set portal

---

data-collection/data-collection/Extensions/ArcGIS/AGSPopupAttachmentSize/AGSPopupAttachmentSize+String.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupAttachmentsViewController/RichPopupAttachmentsViewController+UITableViewDataSource.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupEditStagedPhotoAttachmentViewController/RichPopupEditStagedAttachmentViewController.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/RichPopup.storyboard

In editing an image attachment preferred content size, up-scales output string with the device's main screen scale. This more accurately reflects the image scaling performed by the SDK.

Supports image attachment preferred content size with device screen scale

---

data-collection/data-collection/Rich Popup/Attachments/RichPopupAttachmentsManager.swift
data-collection/data-collection/Rich Popup/Attachments/RichPopupStagedPhotoAttachment.swift
data-collection/data-collection/Rich Popup/RichPopupManager.swift

Implements adding photo attachment using [addAttachmentWithUIImagePickerControllerInfoDictionary](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_popup_attachment_manager.html#a23bfef7aaa1e99770ccc6c9566cb4ade) rather than [addAttachmentAsJPGWithImage](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_popup_attachment_manager.html#a9606cea7ec9b1a1d20cd5da1e52e15a4).
See https://github.com/Esri/data-collection-ios/issues/171

Supports all static image types retrieved from UIImagePickerController

---

data-collection/data-collection/Extensions/UIKit/UIControlState/UIControlState+Hashable.swift

`Hashable.hashValue` has been deprecated. The replacement is `hash(into:)`, which could be implemented as follows:
```swift
public func hash(into hasher: inout Hasher) {
hasher.combine(rawValue)
}
```
However, the standard library provides an implementation. From the documentation for `RawRepresentable` (to which `UIControl.State` conforms): "Available when `Self` conforms to `Hashable` and `RawValue` conforms to `Hashable`."

Use implementation of hash(into:) provided by the standard library

---

data-collection/data-collection/Custom Views/ShrinkingView.swift
data-collection/data-collection/View Controllers/Map View Controller/MapViewController+MapViewMode.swift
data-collection/data-collection/View Controllers/Map View Controller/MapViewController+Setup.swift
data-collection/data-collection/View Controllers/Map View Controller/MapViewController+SmallPopupView.swift
data-collection/data-collection/View Controllers/Map View Controller/MapViewController.storyboard
sdk_build

The lack of this feature has bugged me for a while. Before now, to dismiss a currently selected pop-up, a user would have to select an area of the map where there are no identifiable features. Now the user can touch-drag up or down past a threshold (of 60 points) to dismiss the small pop-up view.
Asking for review from @philium and @nixta for code quality and from @mikewilburn for usability. Of course, these review delineations can blur, if you like.

Small pop-up view touch-drag event dismiss behavior

---

data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController.swift

Because iOS 13 introduces a new modal presentation design, we need to specify if the rich pop-up view controller can be swipe-dismissed or not. We want to allow swipe-dismiss if the user is not editing the rich pop-up and disallow swipe-dismiss if the user is editing the rich pop-up.
_Note. Xcode 11 beta is required to compile this change._

Consider new modal presentation dismissal regarding rich pop-up view controller editing

---

data-collection/data-collection/AppLocation.swift
data-collection/data-collection/Extensions/ArcGIS/AGSDrawStatus/AGSDrawStatus+CustomStringConvertible.swift
data-collection/data-collection/Extensions/ArcGIS/AGSJobStatus/AGSJobStatus+CustomStringConvertible.swift
data-collection/data-collection/Extensions/ArcGIS/AGSLicense/AGSLicense+Description.swift
data-collection/data-collection/Extensions/ArcGIS/AGSLoadStatus/AGSLoadStatus+CustomStringConvertible.swift
data-collection/data-collection/Extensions/ArcGIS/AGSPopup/AGSPopup+Sort.swift
data-collection/data-collection/Extensions/ArcGIS/AGSPopupAttachmentSize/AGSPopupAttachmentSize+String.swift
data-collection/data-collection/Extensions/ArcGIS/AGSPopupAttachmentType/AGSPopupAttachmentType+Icon.swift
data-collection/data-collection/Extensions/UIKit/UIView/UIView+StackViewAutoLayout.swift

Updating app for Swift 5 [SE-0192](https://github.com/apple/swift-evolution/blob/master/proposals/0192-non-exhaustive-enums.md).
According to the [migration guide:](https://swift.org/migration-guide-swift5/)
> n Swift 5 mode, switches over enums, declared in Objective-C or coming from system frameworks, are required to handle “unknown cases”, i.e. cases that might be added in the future, or that may be defined “privately” in an Objective-C implementation file. (Formally, Objective-C allows storing any value in an enum as long as it fits in the underlying type.) These “unknown cases” can be handled by using the new @unknown defaultcase, which still provides warnings if any known cases are omitted from the switch. They can also be handled using a normal default.

Swift 5 non exhaustive enums

---

data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupEditStagedPhotoAttachmentViewController/RichPopupEditStagedAttachmentViewController.swift

#188 
The regular expression used to find illegal characters:  ^[\\^\\\\:\\/*?\"<>|]+$
So Essentially:  ^\:/*?"<>|
Note that for iOS, whitespace is a valid character.

Add check for illegal attachment name characters.

---

data-collection/data-collection/Utilities/ImagePickerPermissions.swift
data-collection/data-collection/View Controllers/App Container/AppContainerViewController.swift
data-collection/data-collection/View Controllers/Map View Controller/MapViewController+LocationSelection.swift

https://github.com/Esri/data-collection-ios/issues/209
Resolution was to pass the `UIBarButtonItem` along to the `userRequestsAddNewFeature` method for selecting a layer to add the new feature too.
For the image source selection, the `UIAlertController` was changed from a `.actionSheet` to a `.alert` as there was no appropriate, easily-accessible UI component to use as a source view/rect.

popover attachment issue

---

data-collection/data-collection.xcodeproj/xcshareddata/xcschemes/data-collection.xcscheme

Turn off metal validation to fix iOS 12 device crash.

Turn off metal validation to fix iOS 12 device crash.

---

data-collection/data-collection/App Context/AppContext.swift

Avoid nullify map if user cancelled Log in OAuth process. Otherwise user need to kill the app and launch it again in order to be able to continue using it.

Avoid nullify map if user cancelled Log in

---

RELEASE.md
data-collection/data-collection/App Context/AppContext+Login.swift
data-collection/data-collection/App Context/AppContext+VisibleArea.swift
data-collection/data-collection/App Context/AppContext+WorkMode.swift
data-collection/data-collection/App Context/AppContext.swift
data-collection/data-collection/AppConfiguration.swift
data-collection/data-collection/AppDelegate.swift
data-collection/data-collection/AppFiles.swift
data-collection/data-collection/AppReachability.swift
data-collection/data-collection/Geocode Search/AppReverseGeocoderManager.swift
data-collection/data-collection/View Controllers/App Container/AppContainerViewController+MapDelegate.swift

This PR accomplishes a number of tasks for improving the brevity and readability of static configuration tasks.
Swaps `class AppConfiguration` and `AppFiles.OfflineDirectoryComponents` for a series of static `String` and `URL` extensions. This technique allows for brevity through type inference. For example:
```diff
- try AGSArcGISRuntimeEnvironment.setLicenseKey(AppConfiguration.licenseKey)
+ try AGSArcGISRuntimeEnvironment.setLicenseKey(.licenseKey)
```

App configuration: brevity

---

data-collection/data-collection/App Context/AppContext+Login.swift

Data Collection to support clearing and revoking credential -   As of 100.6, Runtime introduced a method to [clear and revoke credentials](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_credential_cache.html#a0796cf2506fa0edfdeb2b62198bbbea7). This introduction came after the initial general release of Data Collection. Calling this method revokes the portal user's credential on the server side.
Let's retroactively revisit Data Collection to ensure this method is called when a user requests to log out. 
Additional considerations should be made to ensure that services that have been supplied a previously valid credential will issue a challenge again after that credential is revoked.

Use credentialCache.removeAndRevokeAllCredentials when signing out.

---

data-collection/data-collection.xcodeproj/project.pbxproj

This makes sure they get built before the data-collection target is built.

Add ArcGISToolkit and Alamofire as dependencies

---

README.md
RELEASE.md
data-collection/data-collection.xcodeproj/project.pbxproj
data-collection/data-collection/App Context/AppContextAwareNavigationController.swift
data-collection/data-collection/Utilities/ImagePickerPermissions.swift
data-collection/data-collection/View Controllers/Profile View Controller/ProfileViewController.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/RichPopupDetailsViewController+UITableViewDataSource.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController.swift

This PR drops support for iOS 12, removes properties deprecated by iOS 13, and increments the deployment target to iOS 13.
[[Related Issue]](https://github.com/ArcGIS/open-source-apps/issues/458)

Increment deployment target from iOS 12 to 13

---

data-collection/data-collection.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Alamofire will is removed in the `v.next-1.3` release branch. However for now, Alamofire remains an active dependency. As such, we should commit the `Package.resolved` file to vc.

Introduces Package.resolved file

---

RELEASE.md
data-collection/data-collection/View Controllers/Rich Popup View Controllers/SegmentedViewController.swift

Fixes bug where added target does not perform selector when `.valueChanged` event occurs. This PR lazily initializes `segmentedControl`, guaranteeing `self` is fully initialized before adding the target.

Segmented control bug

---

RELEASE.md
data-collection/data-collection.xcodeproj/project.pbxproj
data-collection/data-collection/AppColors.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/RichPopupDetailsViewController+UITableViewDataSource.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/Table Cells/Attribute Cells/PopupAttributeDateCell.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/Table Cells/Attribute Cells/PopupAttributeDatePickerCell.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/RichPopup.storyboard

This PR introduces enhanced support for pop-up date attribute editing.
1. Introduces new table cell, `PopupAttributeDatePickerCell`, for use by devices running iOS 14. This cell leverages the new iOS 14 `UIDatePicker`, placing the UI element within the attribute cell rather than displaying a date picker in the keyboard area.
1. Introduces support for _time_ as well as date (iOS 13 & 14)
See related issues:
- [[Support for iOS 14]](https://github.com/ArcGIS/open-source-apps/issues/468)
- [[Editing popup date fields to support date and time]](https://github.com/ArcGIS/open-source-apps/issues/472)
| iOS 13 | iOS 14 - in-line | iOS 14 - expanded |
| --- | --- | --- |
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-25 at 14 03 …

Enhanced support for pop-up date attribute editing

---

RELEASE.md
data-collection/data-collection/View Controllers/Map View Controller/MapViewController.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController+EditingSession.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController.swift

This PR resolves the bug, ['Data Collection iOS, deleted pop-up remains in small pop-up view after delete is performed and full pop-up view is dismissed'](https://github.com/ArcGIS/open-source-apps/issues/482).
The solution uses a Combine `PassthroughSubject` to broadcast when edits are made. Subscribers are notified after an add/update/delete operation.

Post Pop-up Editing Bug

---

RELEASE.md
data-collection/data-collection/Address Locator/AddressLocator.swift
data-collection/data-collection/App Context/AppContext.swift

A bug was found.
> The app crashes in a scenario where the app is working **online**, the user is **not authenticated**, and the user attempts to create a new feature thus triggering an authentication challenge to access the world geocoding service. Steps to repro:
> 
> 1. Work online
> 1. Sign-out
> 1. Create a new feature
> 1. Respond to authentication challenge with valid credentials
> 
> At this point the app should crash.
As it was, if the user tried to create a new feature and the online locator was not credentialed, the online locator would issue an authentication challenge. Upon successful authentication, the `AppContext` would rebuild the map using the authenticated portal; doing so would invalidate the created feature because it was a new child of a table that no longer existed …

Fix online locator authentication challenge.

---

data-collection/data-collection/View Controllers/Rich Popup View Controllers/SegmentedViewController.swift

In the console I'm seeing a warning for `UITableViewAlertForLayoutOutsideViewHierarchy`.  This happens when a `layoutIfNeeded` call is applied to a view not yet added to a superview.

Mhd/fix UI table view alert for layout outside view hierarchy

---

data-collection/data-collection/AppDelegate.swift

U11 deprecates the method,
```swift
AGSApplicationDelegate.shared().application(app, open: url, options: options)
```
This PR removes this method call and updates the language surrounding the oauth app delegate open url method.

U11 Cert task- removes deprecated method

---

data-collection/data-collection/View Controllers/Floating Panel View Controller/FloatingPanelController.swift
data-collection/data-collection/View Controllers/Map View Controller/MapViewController.swift

This simple PR sets the floating panel's initial frame off the bottom of the screen creating an effect where the floating panel animates upward or from the top of the screen if non-compact.
Note, I know this is a cheap solution!

Floating Panel Animation

---

data-collection/data-collection/Rich Popup/Attachments/RichPopupAttachmentsManager.swift
data-collection/data-collection/Rich Popup/Attachments/RichPopupStagedAttachment.swift
data-collection/data-collection/Rich Popup/Attachments/RichPopupStagedImagePickerAttachment.swift
data-collection/data-collection/Rich Popup/Attachments/RichPopupStagedPhotoPickerAttachment.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController+AttachmentPicker.swift

With the introduction of support for `NSItemProvider` (vis-a-vis `PHPickerViewController`) via the [`AGSPopupAttachmentManager`](https://developers.arcgis.com/ios/api-reference/interface_a_g_s_popup_attachment_manager.html#a497ae60d61d114d01bccab977688038b), this PR defers the burden of handing item provider image loading to the SDK.

Updates app with Runtime support for NSItemProvider

---

data-collection/data-collection/Utilities/GlobalAlertQueue.swift
data-collection/data-collection/View Controllers/Map View Controller/MapViewController+Map.swift

This adds back in a "sign in alert" for use when attempting to load a private web map.  This functionality existed v1.2.3, but was removed (inadvertently?) when moving to the `GlobalAlertQueue`.

Fix for not prompting user to sign in when opening private map.

---

data-collection/data-collection/View Controllers/Layer Contents View Controllers/LayerContentsTableViewController.swift

Fixes the issue with label colors in the Layers View in dark mode.  Now it uses adaptive colors and defines static values for those colors in the `LayerCell` object.

Use adaptive colors when showing enabled/disabled layer labels.

---

data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupAttachmentsViewController/RichPopupAttachmentsViewController+UITableViewDelegate.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupAttachmentsViewController/RichPopupAttachmentsViewController.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController+AttachmentPicker.swift
data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController+RichPopupAttachmentsViewControllerDelegate.swift

When editing a pop-up and a user selects 'Add Attachment', the app crashes on iPad because the `.actionSheet` requires us to specify a `actionSheet.popoverPresentationController?.sourceView`.
This PR fixes this by supplying the accessory view from the 'Add Attachment' cell (the camera icon) and falls back to the view controller's view if for some reason the accessory view is missing (it shouldn't be!)

iPad: add attachment from source- action sheet bug

---

data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController+AttachmentPicker.swift

The one delegate method for the `PHPickerViewController` is designed to signify both Cancel and Accept operations.  Make sure we handle these two cases.

Fix for [iOS] Can't "Cancel" adding an attachment from Image Library (iOS 14) #573

---

data-collection/data-collection/View Controllers/Identify Results View Controller/IdentifyResultsViewController.swift

Force subtitle for selected row to be regenerated next time through, just in case there were any edits to the feature.
@esreli This was the best quick-fix for the subtitle not being updated.  I wanted to use the `EditsMade` mechanism, but because of the hierarchical nature of the `PopupViewController` -> `PopupDetailViewController` UI stack, it was not easy, straightforward, or risk free.
With this fix, when the cell represented the edited feature is reloaded, the subtitle will update.  So now the subtitle and the swatch will behave the same.

Subtitle update
