Esri/data-collection-ios

- data-collection/data-collection.xcodeproj/project.pbxproj
- data-collection/data-collection/AppContext/AppContext.swift
- data-collection/data-collection/AppDelegate.swift
- data-collection/data-collection/Custom Views/ActivityBarView.swift
- data-collection/data-collection/Custom Views/PinDropView.swift
- data-collection/data-collection/Extensions/UIKit/UIButton/UIButton+AttributedTitle.swift
- data-collection/data-collection/Extensions/UIKit/UIButton/UIButton+ImageTint.swift
- data-collection/data-collection/Extensions/UIKit/UIControlState/UIControlState+Hashable.swift
- data-collection/data-collection/Extensions/UIKit/UIViewController/UIViewController+Alert.swift
- data-collection/data-collection/Geocode Search/AppReverseGeocoderManager.swift
- data-collection/data-collection/View Controllers/App Container/AppContainerViewController.swift
- data-collection/data-collection/View Controllers/Drawer View Controller/DrawerViewController.swift
- data-collection/data-collection/View Controllers/Map View Controller/MapViewController+LocationSelection.swift
- data-collection/data-collection/View Controllers/Map View Controller/MaskViewController.swift
- data-collection/data-collection/View Controllers/Related Records View Controllers/Related Records Popups View Controller/Delete Cell/DeleteRecordCell.swift
- data-collection/data-collection/View Controllers/Related Records View Controllers/Related Records Popups View Controller/Field Cells/Base/PopupReadonlyFieldCell.swift
- data-collection/data-collection/View Controllers/Related Records View Controllers/Related Records Popups View Controller/Related Records Cell/RelatedRecordCell.swift
- data-collection/data-collection/View Controllers/Related Records View Controllers/Related Records Popups View Controller/RelatedRecordsPopupsViewController+Delegate.swift
- data-collection/data-collection/View Controllers/Related Records View Controllers/Related Records Popups View Controller/RelatedRecordsPopupsViewController+EditingSessions.swift
- data-collection/data-collection/View Controllers/Related Records View Controllers/Related Records Popups View Controller/RelatedRecordsPopupsViewController.swift
Migration performed following these steps:
1. Use Swift 4.2 migrator assistant.
2. Updates for use of `Bool.toggle()`
3. Updates for use of Swift 4.2 syntax unwrapping of weak self.
Other swift 4.2 migration suggestions welcomed.
> Migrates project to Swift 4.2

- data-collection/data-collection/Custom Views/ActivityBarView.swift
- data-collection/data-collection/View Controllers/Map View Controller/MapViewController.swift
This improves the activity bar API as well removing the redundant update for new color call.
> improves activity bar setting colors and animations

- data-collection/data-collection/View Controllers/Map View Controller/MapViewController+Map.swift
References this issue: https://github.com/Esri/data-collection-ios/issues/140
> Fixes log in typo.

- data-collection/data-collection.xcodeproj/project.pbxproj
- data-collection/data-collection/AppContext/AppContext+Login.swift
- data-collection/data-collection/Extensions/ArcGIS/AGSMap/AGSMap+GeodatabaseFeatureTable.swift
- data-collection/data-collection/Extensions/ArcGIS/AGSMap/AGSMap+RemoteResource.swift
This PR references this issue:
https://github.com/Esri/data-collection-ios/issues/141
The steps to repro are contained within the issue.
> Removes credentials for every AGSServiceFeatureTable upon logout

- data-collection/data-collection.xcodeproj/project.pbxproj
Executes build script that updates the `sdk_build` file build number to that of the currently installed SDK.
> Adds Build Script: SDK Build Number

- data-collection/data-collection/View Controllers/Map View Controller/MapViewController+Map.swift
This PR addresses this enhancement request:
https://github.com/Esri/data-collection-ios/issues/152
> Ensures when offline map loads that it is at least partially visible.

- data-collection/data-collection/View Controllers/App Container/AppContainerViewController+MapDelegate.swift
- data-collection/data-collection/View Controllers/Map View Controller/MapViewController+Map.swift
This PR addresses this issue: 
https://github.com/Esri/data-collection-ios/issues/152
From @mikewilburn 's recommendation, following this question: 
https://github.com/Esri/data-collection-ios/issues/152#issuecomment-438101031
I have implemented solution **a)**.
I've also added code comments that document what is happening and why.
> Same min and max scale for online and offline maps.

- data-collection/data-collection/View Controllers/Map View Controller/MapViewController.storyboard
Will auto-merge without review because of how marginally small this change is.
> Updates background color of add related record button to 'primary'.

- data-collection/data-collection/AppConfiguration.swift
- data-collection/data-collection/Custom Behavior/CustomBehavior_Map.swift
This PR provides a new publicly-accessible web map which does not have custom edits applied in the course of developmental testing.
> Provide new web map ID

- data-collection/data-collection/View Controllers/Rich Popup View Controllers/RichPopup.storyboard
Before:
_(note the ellipsis)_
After:
_(note the reduced font size)_
> sets minimum font scale for attachment names

- data-collection/data-collection/App Context/AppContext+WorkMode.swift
- data-collection/data-collection/Extensions/ArcGIS/AGSPopup/AGSPopup+Comparison.swift
Leaving the contents of the `do` clause, obviously. Of those lines, only the indentation was changed.
> Removes do…catch statements that were only rethrowing the error

- data-collection/data-collection/App Context/AppContext+Login.swift
- data-collection/data-collection/App Context/AppContext.swift
- data-collection/data-collection/AppDelegate.swift
- data-collection/data-collection/Extensions/ArcGIS/AGSPortal/AGSPortal+CachedCredentials.swift
- data-collection/data-collection/Extensions/UIKit/UIViewController/UIViewController+Alert.swift
- data-collection/data-collection/View Controllers/App Container/AppContainerViewController+DrawerDelegate.swift
- data-collection/data-collection/View Controllers/Drawer View Controller/DrawerViewController.storyboard
- data-collection/data-collection/View Controllers/Drawer View Controller/DrawerViewController.swift
- data-collection/data-collection/View Controllers/Map View Controller/MapViewController+Map.swift
TLDR;
"Sign in" is the verb, "Login" is the noun.
> Updates copy to reflect the ArcGIS style guide concerning usage of "sign in".

- data-collection/data-collection/App Context/AppContext+Login.swift
- data-collection/data-collection/Extensions/ArcGIS/AGSPortal/AGSPortal+CachedCredentials.swift
@esreli I was too slow to review #189, so opening this PR with a couple of minor edits that were overlooked in the original.
> Additional sign in updates

- data-collection/data-collection/3rd Party/Alamofire/NetworkReachabilityManager.swift
https://github.com/Alamofire/Alamofire/blob/master/Source/NetworkReachabilityManager.swift
> Updates app with latest Alamofire NetworkReachabilityManager

- data-collection/data-collection/View Controllers/AppContextAwareNavigationController.swift
The iOS 13 UINavigationBarAppearance API allows a developer to customize the appearance of the navigation bar with more granularity.
This PR ensures the app performs to spec when ran on a device with iOS 13 installed.
https://developer.apple.com/documentation/uikit/uinavigationbarappearance
> Adopts iOS 13 UINavigationBarAppearance API

- data-collection/data-collection.xcodeproj/project.pbxproj
- data-collection/data-collection/Extensions/UIKit/UIAlertController/UIAlertAction.swift
- data-collection/data-collection/Extensions/UIKit/UIAlertController/UIAlertController+Alert.swift
- data-collection/data-collection/Utilities/ImagePickerPermissions.swift
- data-collection/data-collection/View Controllers/App Container/AppContainerViewController+DrawerDelegate.swift
- data-collection/data-collection/View Controllers/Map View Controller/MapViewController+LocationSelection.swift
As a result, the action titles and styles only have to be specified in one place.
> Consolidate creation of OK and Cancel actions

- README.md
> Rename example apps

- RELEASE.md
- data-collection/Resources/Info.plist
- data-collection/data-collection.xcodeproj/project.pbxproj
Just like the title says:
- updated version to 1.1.2
- updated Release.md file with release notes (two issues fixed)
> Update version to 1.1.2; update Release.md file.

- RELEASE.md
Add release notes regarding certification for the 100.7.0 SDK release.
> 1.1.3 Release notes for 100.7 SDK Release

- data-collection/data-collection/Extensions/ArcGIS/AGSPopup/AGSPopup+RecordType.swift
- data-collection/data-collection/View Controllers/Map View Controller/MapViewController+SmallPopupView.swift
- data-collection/data-collection/View Controllers/Map View Controller/MapViewController.swift
Fixes the `featureTable.featureLayer` deprecation warning.
> fix featureLayer deprecation warning.

- data-collection/data-collection.xcodeproj/project.pbxproj
> Use new bundle identifier.

- data-collection/data-collection/App Errors/LoadablesError.swift
> Fix buildtime issue when building with Xcode 11.4

- data-collection/data-collection/App Context/AppContext+WorkMode.swift
- data-collection/data-collection/AppFiles.swift
- data-collection/data-collection/AppGlobals.swift
- data-collection/data-collection/View Controllers/Map View Controller/MapViewController+LocationSelection.swift
Converts `AppFiles` type to `FileManager` extension, accomplishing the same task.
> Converts `AppFiles` to `FileManager` extension

- data-collection/data-collection/Rich Popup/Related Records/Relationship.swift
- data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupViewController+RichPopupDetailsViewControllerDelegate.swift
This PR improves the type `Relationship` in a few ways.
- Establish `Relationship.MissingRelationship` error type
- Improves how Errors are managed by the class
- Improves `Relationship.queryAndSortAllRelatedPopups` to leverage swift Result type
> AppErrors: migrating Relationship conformance and general improvements

- README.md
Updates the documentation regarding Lite license level; offline editing and syncing require a Basic license.
> License level clarification

- data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/Table Cells/Related Record Cells/PopupRelatedRecordCell.swift
- data-collection/data-collection/View Controllers/Rich Popup View Controllers/RichPopup.storyboard
- data-collection/data-collection/View Controllers/Rich Popup View Controllers/SegmentedViewController.swift
This PR introduces system colors and blur effects to adapt the view controller to Dark Mode.
> Rich Popup View Controller to Dark Mode

- docs/README.md
- The code snippets have changed or could change, this is a sustainability concern
- Added or elaborated on some concepts
> Updates docs removing code snippets and inserting missing items

- data-collection/data-collection/View Controllers/Rich Popup View Controllers/Rich Popup View Controller/RichPopupDetailsViewController/Table Cells/Attribute Cells/PopupAttributeDatePickerCell.swift
This PR addresses this issue, https://github.com/ArcGIS/open-source-apps/issues/572
> Fix Date Picker initial value
